-- MySQL Script generated by MySQL Workbench
-- sáb 05 dez 2020 11:20:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bitnami_wordpress
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bitnami_wordpress
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bitnami_wordpress` ;
USE `bitnami_wordpress` ;

-- -----------------------------------------------------
-- Table `bitnami_wordpress`.`child`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bitnami_wordpress`.`child` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `birth_date` DATE NOT NULL,
  `tutor_name` VARCHAR(128) NOT NULL,
  `tutor_phone` VARCHAR(32) NOT NULL,
  `tutor_email` VARCHAR(64) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bitnami_wordpress`.`subitem_unit_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bitnami_wordpress`.`subitem_unit_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT 'kg, cm, mmHg',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bitnami_wordpress`.`item_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bitnami_wordpress`.`item_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `code` VARCHAR(32) NOT NULL COMMENT 'manually fill with values: child_data, diagnosis, intervention, evaluation',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bitnami_wordpress`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bitnami_wordpress`.`item` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `item_type_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `state` ENUM('active','inactive') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_item_item_type1_idx` (`item_type_id` ASC),
  CONSTRAINT `fk_item_item_type1`
    FOREIGN KEY (`item_type_id`)
    REFERENCES `bitnami_wordpress`.`item_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bitnami_wordpress`.`subitem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bitnami_wordpress`.`subitem` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL DEFAULT '',
  `item_id` INT UNSIGNED NOT NULL,
  `value_type` ENUM('text','bool','int','double','enum') NOT NULL COMMENT 'text, int, double, boolean, enum',
  `form_field_name` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'ascii string to be used as the name of the form field',
  `form_field_type` ENUM('text','textbox','radio','checkbox','selectbox') NOT NULL,
  `unit_type_id` INT UNSIGNED NULL,
  `form_field_order` INT UNSIGNED NOT NULL COMMENT 'order in which form fields will be shown',
  `mandatory` INT NOT NULL COMMENT '1 if subitem is mandatory for its parent, 0 if not',
  `state` ENUM('active','inactive') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subitem_unit_type_idx` (`unit_type_id` ASC),
  INDEX `fk_subitem_item1_idx` (`item_id` ASC),
  CONSTRAINT `fk_subitem_unit_type`
    FOREIGN KEY (`unit_type_id`)
    REFERENCES `bitnami_wordpress`.`subitem_unit_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subitem_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `bitnami_wordpress`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bitnami_wordpress`.`subitem_allowed_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bitnami_wordpress`.`subitem_allowed_value` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `subitem_id` INT UNSIGNED NOT NULL,
  `value` VARCHAR(128) NOT NULL,
  `state` ENUM('active','inactive') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subitem_allowed_value_subitem1_idx` (`subitem_id` ASC),
  CONSTRAINT `fk_subitem_allowed_value_subitem1`
    FOREIGN KEY (`subitem_id`)
    REFERENCES `bitnami_wordpress`.`subitem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bitnami_wordpress`.`value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bitnami_wordpress`.`value` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `child_id` INT UNSIGNED NOT NULL,
  `subitem_id` INT UNSIGNED NOT NULL,
  `value` VARCHAR(8192) NOT NULL,
  `date` DATE NOT NULL,
  `time` TIME NOT NULL,
  `producer` VARCHAR(64) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_value_child1_idx` (`child_id` ASC),
  INDEX `fk_value_subitem1_idx` (`subitem_id` ASC),
  CONSTRAINT `fk_value_child1`
    FOREIGN KEY (`child_id`)
    REFERENCES `bitnami_wordpress`.`child` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_value_subitem1`
    FOREIGN KEY (`subitem_id`)
    REFERENCES `bitnami_wordpress`.`subitem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
